#! /bin/bash

# run smoketest for the docker image. port 8545 must be available.
# make sure the docker image has already been build with
#
#     docker build -t contracts .

set -x

docker run -d -p 8545:8545 --name ganache --rm trufflesuite/ganache:latest
sleep 3
docker run --net="host" contracts
retval=$?
docker logs ganache
docker stop ganache
exit $retval
