#! /bin/bash

# run smoketest for the docker image. port 8545 must be available.
# make sure the docker image has already been build with
#
#     docker build -t contracts .

set -x

container=$(docker run -d -p 8545:8545 --entrypoint '' --rm parity/parity:v2.4.6 bash -c 'echo >/tmp/empty-password; parity --no-color --jsonrpc-apis=all --jsonrpc-hosts=all --jsonrpc-interface 0.0.0.0 --config dev --unlock 0x00a329c0648769a73afac7f9381e08fb43dbea72 --password=/tmp/empty-password')
sleep 3
docker run --net="host" contracts test
retval=$?
docker logs -t $container
docker stop $container
exit $retval
