# create docker image for dev chain with unlocked account
# create the parity-dev image with:
#
#     docker build . -f Dockerfile-parity-dev -t parity-dev
#
# and run it with
#
# docker run -p 8545:8545 --rm parity-dev

FROM parity/parity:v1.11.11
RUN echo >/root/empty-password
RUN timeout 3 /parity/parity --no-color --config dev || echo "initialized"
ENTRYPOINT []
CMD ["/parity/parity", "--no-color", "--jsonrpc-apis=all", "--jsonrpc-hosts=all", "--jsonrpc-interface", "0.0.0.0", "--config", "dev", "--unlock", "0x00a329c0648769a73afac7f9381e08fb43dbea72", "--password=/root/empty-password"]
